name: Atualizar VPS e Executar Comando

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  atualizarVPS:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Conectar à VPS e executar comandos
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -p 4927 devplex@62.72.11.140 'bash -s' << 'ENDSSH'
            cd otserver &&
            git pull &&
            screen -d -m -S minha_sessao ./restart.sh
          ENDSSH
        env:
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
